name = "Destruct"
uuid = "dde75ccc-4946-507f-85f2-ccadd28c929c"
authors = ["Samuel Palato <samuel.palato@mail.mcgill.ca>"]
version = "1.1.1"

[deps]

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
